name: myfilms_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.5
  http: ^1.5.0
  flutter_dotenv: ^6.0.0
  google_generative_ai: ^0.4.7
  google_generative_language_api: ^0.2.1
  supabase_flutter: ^2.10.3
  crypto: ^3.0.6
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/key.env
